
application: the-hackathon
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: app.webapp

libraries:
- name: lxml
  version: "latest"
- name: PIL
  version: "latest"
- name: ssl
  version: latest
